name: Deploy Package Repos

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-package-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download latest release artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          mkdir -p artifacts/deb artifacts/rpm artifacts/flatpak
          TAG=$(gh release view --repo frostycoolslug/beacn-utility --json tagName -q .tagName)
          echo "Latest release: $TAG"
          gh release download "$TAG" --repo frostycoolslug/beacn-utility --pattern "*.deb" --dir artifacts/deb
          gh release download "$TAG" --repo frostycoolslug/beacn-utility --pattern "*.rpm" --dir artifacts/rpm
          gh release download "$TAG" --repo frostycoolslug/beacn-utility --pattern "*.flatpak" --dir artifacts/flatpak

      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:flatpak/stable
          
          sudo apt-get update
          sudo apt-get install -y dpkg-dev rpm createrepo-c gnupg flatpak software-properties-common ostree

      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import

      - name: Build Debian repo
        run: |
          BINARY_DIR="repo/deb/dists/stable/main/binary-amd64"
          RELEASE_DIR="repo/deb/dists/stable"
          
          mkdir -p "${BINARY_DIR}"
          cp artifacts/deb/*.deb "${BINARY_DIR}/"

          # Generate Packages index
          cd "${BINARY_DIR}"
          dpkg-scanpackages "${BINARY_DIR}" /dev/null > "${BINARY_DIR}/Packages"
          gzip -c Packages > Packages.gz
          cd -

          # Create Release file at dists/stable/
          RELEASE_FILE="${RELEASE_DIR}/Release"
          
          echo "Suite: stable" > "$RELEASE_FILE"
          echo "Codename: stable" >> "$RELEASE_FILE"
          echo "Architectures: amd64" >> "$RELEASE_FILE"
          echo "Components: main" >> "$RELEASE_FILE"
          echo "Description: The Beacn on Linux APT repository" >> "$RELEASE_FILE"
          echo "Date: $(date -Ru)" >> "$RELEASE_FILE"
          echo "SHA256:" >> "$RELEASE_FILE"

          for file in "${BINARY_DIR}/Packages" "${BINARY_DIR}/Packages.gz"; do
            if [ -f "$file" ]; then
              SIZE=$(stat -c%s "$file")
              HASH=$(sha256sum "$file" | cut -d' ' -f1)
              REL_PATH="${file#${RELEASE_DIR}/}"
              echo " $HASH $SIZE ${REL_PATH}" >> "$RELEASE_FILE"
            fi
          done
          
          # Sign Packages and Release files
          gpg --batch --yes -u "Beacn on Linux" --detach-sign -o "${BINARY_DIR}/Packages.gz.gpg" "${BINARY_DIR}/Packages.gz"
          gpg --batch --yes -u "Beacn on Linux" --detach-sign -o "${RELEASE_FILE}.gpg" "${RELEASE_FILE}"
          gpg --batch --yes -u "Beacn on Linux" --clearsign -o "${RELEASE_DIR}/InRelease" "${RELEASE_FILE}"

      - name: Build RPM repo
        run: |
          echo "%_gpg_name Beacn on Linux" > ~/.rpmmacros
          
          mkdir -p repo/rpm
          cp artifacts/rpm/*.rpm repo/rpm/

          # Sign RPMs
          for pkg in repo/rpm/*.rpm; do
            rpm --addsign "$pkg"
          done

          # Generate metadata
          createrepo_c repo/rpm

      - name: Build Flatpak repo
        run: |
          mkdir -p repo/flatpak
          ostree init --mode=archive --repo=repo/flatpak
          
          for bundle in artifacts/flatpak/*.flatpak; do
            [ -e "$bundle" ] || continue
            flatpak build-import-bundle repo/flatpak "$bundle" --gpg-sign="Beacn on Linux"
          done
          
          flatpak build-update-repo repo/flatpak --gpg-sign="Beacn on Linux" --prune

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./repo

      # eploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
