name: Deploy Package Repos

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-package-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download latest release artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          mkdir -p artifacts/deb artifacts/rpm artifacts/flatpak
          TAG=$(gh release view --repo frostycoolslug/beacn-utility --json tagName -q .tagName)
          echo "Latest release: $TAG"
          gh release download "$TAG" --repo frostycoolslug/beacn-utility --pattern "*.deb" --dir artifacts/deb
          gh release download "$TAG" --repo frostycoolslug/beacn-utility --pattern "*.rpm" --dir artifacts/rpm
          gh release download "$TAG" --repo frostycoolslug/beacn-utility --pattern "*.flatpak" --dir artifacts/flatpak

      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:flatpak/stable
          
          sudo apt-get update
          sudo apt-get install -y dpkg-dev rpm createrepo-c gnupg flatpak software-properties-common ostree

      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import

      - name: Build Debian repo
        run: |
          mkdir -p repo/deb/binary
          cp artifacts/deb/*.deb repo/deb/binary/

          cd repo/deb
          dpkg-scanpackages binary /dev/null > binary/Packages
          gzip -c binary/Packages > binary/Packages.gz

          # Sign Packages
          gpg --batch --yes -u "Beacn on Linux" --detach-sign -o binary/Packages.gz.gpg binary/Packages.gz

          # Create and sign Release files
          echo "Suite: stable" >> Release
          echo "Codename: stable" >> Release
          echo "Architectures: amd64" >> Release
          echo "Components: main" >> Release
          echo "Description: The Beacn on Linux APT repository" >> Release

          gpg --batch --yes -u "Beacn on Linux" --detach-sign -o Release.gpg Release
          gpg --batch --yes -u "Beacn on Linux" -abs -o InRelease Release

      # uild and sign RPM repo
      - name: Build RPM repo
        run: |
          echo "%_gpg_name Beacn on Linux" > ~/.rpmmacros
          
          mkdir -p repo/rpm
          cp artifacts/rpm/*.rpm repo/rpm/

          # Sign RPMs
          for pkg in repo/rpm/*.rpm; do
            rpm --addsign "$pkg"
          done

          # Generate metadata
          createrepo_c repo/rpm

      - name: Build Flatpak repo
        run: |
          mkdir -p repo/flatpak
          ostree init --mode=archive --repo=repo/flatpak
          ostree remote add beacn-on-linux repo/flatpak
          
          for bundle in artifacts/flatpak/*.flatpak; do
            [ -e "$bundle" ] || continue
            flatpak build-import-bundle repo/flatpak "$bundle" --gpg-sign="Beacn on Linux"
          done
          
          flatpak build-update-repo repo/flatpak --gpg-sign="Beacn on Linux" --prune

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./repo

      # eploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
